dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2
  - frontend/src/bower_components
  - frontend/src/node_modules
  - integration/rocket-chat/node_modules

services:
  - mongodb

jdk:
  - openjdk8

before_install:
  - gem install sass
  - gem install compass

install:
  - mvn -B clean install -Dquick

script:
  - mvn -B -DargLine="-Xmx2g" test



